#!/bin/ksh

cmd="${1:?cmd}"
zone="${2:?zone}"
root="${3:?root}"
shift 3

bhyve_shutdown()
{
	typeset delay=${1:-60}
	pkill -z "$zone" bhyve
	while [ $delay -gt 0 ] && pgrep -z "$zone" bhyve >/dev/null; do
		((delay = delay - 1))
		sleep 1
	done
}

case $cmd in
    shutdown)
	bhyve_shutdown 0
	;;
    prestate)
	case $1:$2 in
	    4:4) # halting (even as part of rebooting)
		bhyve_shutdown 60
		;;
	esac
	;;
    poststate)
	;;
esac

exit 0

