#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# Copyright 2020 OmniOS Community Edition (OmniOSce) Association.

. /usr/lib/brand/shared/log.ksh
. /usr/lib/brand/shared/util.ksh

ZONENAME="$1"
ZONEPATH="$2"

[ -n "$ZONEPATH" -a -d "$ZONEPATH" ] || fatal "$ZONEPATH is not a directory"

ZONEPATH_DS=`zonepath_to_ds "$ZONEPATH"`
if [ -n "$ZONEPATH_DS" ]; then
	zfs destroy -r $ZONEPATH_DS || exit $ZONE_SUBPROC_FATAL
elif [ -d "$ZONEPATH" ]; then
	rm -rf "$ZONEPATH"
fi

exit $ZONE_SUBPROC_OK
