#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# Copyright 2016 Joyent, Inc.  All rights reserved.
# Copyright 2016 OmniTI Computer Consulting, Inc.  All rights reserved.
# Copyright 2021 OmniOS Community Edition (OmniOSce) Association.
#

PATH=/usr/bin:/usr/sbin:$PATH
export PATH

. /usr/lib/brand/shared/common.ksh
. /usr/lib/brand/shared/log.ksh
. /usr/lib/brand/shared/image.ksh
. /usr/lib/brand/shared/vars.ksh

function usage
{
	[ -n "$*" ] && echo "$*" && echo
	cat << EOM
Available options are:
	-s <dataset|snapshot|pathname>	Zone installation source
	(-t is a backwards compatible alias for -s)

EOM
	# Use FATAL and not USAGE to prevent the default usage message
	exit $ZONE_SUBPROC_FATAL
}

while getopts "R:s:t:z:v" opt; do
	case "$opt" in
		R)	ZONEPATH="$OPTARG" ;;
		z)	ZONENAME="$OPTARG" ;;
		s|t)	SEEDSRC="$OPTARG" ;;
		v)	OPT_V=1 ;;
		*)	usage ;;
	esac
done
shift OPTIND-1

[ -n "$ZONENAME" ] || usage 'No zone name supplied.'
[ -n "$ZONEPATH" ] || usage 'No zone path supplied.'
[ -n "$SEEDSRC" ] || usage 'The installation source must be specified.'

seed_zone --withbe=illumos "$ZONENAME" "$ZONEPATH" "$SEEDSRC"

# This zone's boot environments need to be fully independant of the global
# zone's boot environments.
# Generate a new UUID to assign as the parent BE, and store it on the ROOT
# dataset too for use during zone boot.
typeset zoneds=`zonepath_to_ds_chk "$ZONEPATH"`
typeset uuid=`uuidgen`
zfs set org.opensolaris.libbe:uuid=$uuid $zoneds/ROOT
zfs set $PROP_PARENT=$uuid $zoneds/ROOT/illumos

exit $ZONE_SUBPROC_OK

