#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# Copyright 2021 OmniOS Community Edition (OmniOSce) Association.

. /usr/lib/brand/ipkg/common.ksh
. /usr/lib/brand/shared/vars.ksh

ZONENAME="$1"
ZONEPATH="$2"
state="$3"
cmd="$4"
ALTROOT="$5"

typeset ds=`zonepath_to_ds_chk $ZONEPATH`
gzuuid=`zfs get -pH -o value org.opensolaris.libbe:uuid $ds/ROOT 2>/dev/null`
[ "$gzuuid" = "-" ] && gzuuid=
function get_current_gzbe { CURRENT_GZBE="$gzuuid"; }

case $cmd in
    $ZONE_STATE_CMD_READY)
	# Old-style illumos zones (without BE support) do not have a
	# UUID or active dataset.
	[ -n "$gzuuid" ] && mount_active_ds
	config_network
	;;
esac

exit $ZONE_SUBPROC_OK
