#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# Copyright 2021 OmniOS Community Edition (OmniOSce) Association.

. /usr/lib/brand/ipkg/common.ksh
. /usr/lib/brand/shared/vars.ksh

zonename=$1
zonepath=$2
cmd=$3

case $cmd in
    datasets)
	typeset ds=`zonepath_to_ds_chk $zonepath`
	z=`zfs list -H -t filesystem -o name $ds/ROOT 2>/dev/null`
	# Old-style illumos zones will not have boot environments, so just
	# return an empty list in that case.
	[ -n "$z" ] && printf "%s" $z
	;;
esac

exit $ZONE_SUBPROC_OK

