#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# Copyright 2019 OmniOS Community Edition (OmniOSce) Association.

ZONENAME="$1"
ZONEPATH="$2"

ZONEPATH_DS=`zfs list -t filesystem -o name,mountpoint | \
    nawk -v zonepath=$ZONEPATH '$2 == zonepath { print $1 }'`
if [ -n "$ZONEPATH_DS" ]; then
	zfs destroy -r $ZONEPATH_DS || exit $ZONE_SUBPROC_FATAL
fi

exit $ZONE_SUBPROC_OK
