#!/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2008, 2011, Oracle and/or its affiliates. All rights reserved.
# Copyright 2017 OmniOS Community Edition (OmniOSce) Association.
#

. /usr/lib/brand/sparse/common.ksh

m_usage=$(gettext  "detach [-n ].")

f_mount=$(gettext "Error: error mounting zone root dataset.")
f_ds_config=$(gettext  "Failed to configure dataset %s: could not set %s.")

noexecute=0

# Other brand detach options are invalid for this brand.
while getopts "nR:z:" opt; do
	case $opt in
		n)	noexecute=1 ;;
		R)	zonepath="$OPTARG" ;;
		z)	zonename="$OPTARG" ;;
		?)	fail_usage "" ;;
		*)	fail_usage "";;
	esac
done
shift $((OPTIND-1))

if [ $noexecute -eq 1 ]; then
	# dry-run - output zone's config and exit
	cat /etc/zones/$zonename.xml
	exit $ZONE_SUBPROC_OK
fi

ZONEPATH=$zonepath
ZONENAME=$zonename

#
# Detaching
#
# Leave the active dataset mounted on the zone's rootpath for ease of
# migration.
#

find_active_ds
umount_overlays
umount_active_ds
mount_active_ds
mount_overlays

/usr/sbin/zfs set zoned=off $ACTIVE_DS || \
    fail_incomplete "$f_ds_config" "$ACTIVE_DS" "zoned=off"

/usr/sbin/zfs set canmount=on $ACTIVE_DS || \
    fail_incomplete "$f_ds_config" "$ACTIVE_DS" "canmount=on"

/usr/sbin/zfs set mountpoint=$zonepath/root $ACTIVE_DS || \
    fail_incomplete "$f_ds_config" "$ACTIVE_DS" "mountpoint=$zonepath/root"

for ov in $overlays; do
	ds=${ov%:*}
	mp=${ov#*:}

	# Don't need to set zoned as it is inherited from the zone root dataset
	/usr/sbin/zfs set canmount=on $ACTIVE_DS/$ds || \
	    fail_incomplete "$f_ds_config" "$ACTIVE_DS/$ds" "canmount=on"
	/usr/sbin/zfs set mountpoint=$zonepath/root/$mp $ACTIVE_DS/$ds || \
	    fail_incomplete "$f_ds_config" "$ACTIVE_DS/$ds" \
	    "mountpoint=$zonepath/root/$mp"
done

#
# There is no sw inventory in an ipkg branded zone, so just use the original
# xml file.
#
cp /etc/zones/$zonename.xml $zonepath/SUNWdetached.xml

exit $ZONE_SUBPROC_OK
