#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

# Copyright 2019 OmniOS Community Edition (OmniOSce) Association.

. /usr/lib/brand/sparse/common.ksh
. /usr/lib/brand/shared/state.ksh

[ $sparsedebug -eq 1 ] && printf "POSTSTATE $*"

ZONENAME="$1"
ZONEPATH="$2"
state="$3"
cmd="$4"
ALTROOT="$5"

case $cmd in
    $ZONE_STATE_CMD_READY)
	# At this point, the overlay should be mounted ready for boot.
	find_active_ds
	mount_overlays
	setup_fw
	;;
    $ZONE_STATE_CMD_HALT)
	# Re-mount overlays to support patching while zone is down
	find_active_ds
	mount_overlays
	unconfig_network
	;;
esac

exit $ZONE_SUBPROC_OK
