#!/bin/ksh -p
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}

# Copyright 2019 OmniOS Community Edition (OmniOSce) Association.

. /usr/lib/brand/sparse/common.ksh

[ $sparsedebug -eq 1 ] && printf " PRESTATE $*"

ZONENAME=$1
ZONEPATH=$2
state=$3
cmd=$4
ALTROOT=$5

case $cmd in
    0)
	# Going to ready state
	# When this script returns, the active zone dataset must be mounted
	# ready for boot, but the overlays must not be since zoneadm will
	# check for any mounted child filesystems and abort if found.

	find_active_ds
	umount_overlays
	umount_active_ds
	mount_active_ds
	if [ "$state" = 99 ]; then
		# System boot but zone not set to auto boot.
		# Mount overlays so that everything is available for patching.
		mount_overlays
	else
		# Configure the network if the zone is actually heading for boot
		config_network
	fi
	;;
    1)
	# Pre-boot
	;;
esac

exit $ZONE_SUBPROC_OK

# Vim hints
# vim:fdm=marker
