.\" Copyright (c) 2007, 2013, Oracle and/or its affiliates. All rights reserved.
.\" Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
.Dd February 17, 2022
.Dt PKGFMT 1
.Os
.Sh NAME
.Nm pkgfmt
.Nd format a package manifest
.Sh SYNOPSIS
.Nm
.Sm off
.Op Fl c | d | s | u
.Sm on
.Op Fl f Cm v1 Ns | Ns Cm v2
.Op Ar package-manifest-file
.Sh DESCRIPTION
.Nm
without the
.Fl c
or
.Fl d
options formats a package manifest in a consistent manner, including wrapping
lines at 80 characters, sorting lines by attributes.
There are two different output formats -
.Cm v1
and
.Cm v2
- which have different sorting characteristics and are described below.
The default output format is
.Cm v2 .
Lines that do not parse into actions
.Pq such as macros, comments, or transforms
do not appear in sorted order.
.Pp
If no arguments are given,
.Nm
reads
.Dv stdin
until EOF, and then writes the formatted manifest to
.Dv stdout .
Any manifests specified on the command line are formatted in place.
.Pp
.Nm
with the
.Fl c
option checks whether the manifests are formatted in
.Nm
style.
The
.Fl d
option displays the differences if the file is not properly formatted.
.Pp
.Nm
with the
.Fl s
option removes additional diagnostic attributes from actions that are not
required in a published manifest.
.Sh OUTPUT FORMATS
.Nm
supports two different output formats selectable with the
.Fl f
option.
The default format is
.Cm v2 .
.Bl -tag -width offset
.It Cm v1
The
.Cm v1
format places
.Ic set
actions first,
.Ic depend
actions last and all other actions in between, sorted alphabetically.
Actions are secondarily sorted by their primary attribute.
.It Cm v2
The
.Cm v2
format groups actions together into different sections.
The resulting action order is:
.Pp
.Bl -enum -offset Ds -compact
.It
.Ic set
actions
.It
all other actions, sorted by key attribute
.It
.Cm driver ,
.Cm group
and
.Cm user
actions
.It
.Cm legacy
and
.Cm license
actions
.It
.Ic depend
actions.
.El
.Pp
In particular, this format groups
.Cm file ,
.Cm dir ,
.Cm link
and
.Cm hardlink
actions together by path which can aid readability.
.El
.Sh OPTIONS
The following options are supported:
.Bl -tag -width Ds
.It Fl h | \&help | \&?
Display a usage message.
.It Fl c
Check whether the manifest is formatted in the
.Nm
style.
.It Fl d
Display manifest differences from the formatted version in unified form.
.It Fl f Cm v1 Ns | Ns Cm v2
Specify the desired output format.
.It Fl s
Remove unecessary diagnostic attributes from manifest actions.
.It Fl u
Do not wrap lines at 80 characters.
This option is useful for applying traditional text processing tools to package
manifests.
.El
.Sh EXIT STATUS
The following exit values are returned:
.Bl -tag -width Ds
.It 0
Command succeeded.
.It 1
The
.Fl c
or
.Fl d
options were specified, and one or more manifests are not in
.Nm
normal form, or an error occurred.
.It  2
Invalid command line options were specified.
.It 99
An unanticipated exception occurred.
.El
.Sh ENVIRONMENT VARIABLES
The following environment variable is supported:
.Bl -tag -width Ds
.It Ev PKGFMT_OUTPUT
The default output format,
.Cm v1
or
.Cm v2 ,
overriding the built-in default value of
.Cm v2 .
.El
.Sh INTERFACE STABILITY
The command line interface of
.Nm
is
.Sy Uncommitted .
The output of
.Nm
is
.Sy Not-An-Interface
and may change at any time.
.Sh SEE ALSO
.Xr pkg 7
