'\" te
.\" Copyright (c) 2007, 2015, Oracle and/or its affiliates. All rights reserved.
.\" Copyright (c) 2015, OmniTI Computer Consulting, Inc. All rights reserved.
.\" Copyright 2021 OmniOS Community Edition (OmniOSce) Association.
.Dd November 29, 2021
.Dt PKGREPO 1
.Os
.Sh NAME
.Nm pkgrepo
.Nd Image Packaging System repository management utility
.Sh SYNOPSIS
.\" create
.Nm Cm create
.Op Fl \&-version Ar ver
.Ar uri_or_path
.\" add-publisher
.Nm Cm add-publisher
.Fl s Ar repo_uri_or_path Ar publisher No \&...
.\" remove-publisher
.Nm Cm remove-publisher
.Op Fl n
.Op Fl \&-synchronous
.Fl s Ar repo_uri_or_path
.Ar publisher No \&...
.\" get
.Nm Cm get
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar section/property No \&...
.\" info
.Nm Cm info
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.\" list
.Nm Cm list
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar pkg_fmri_pattern No \&...
.\" contents
.Nm Cm contents
.Op Fl m
.Oo Fl t Ar action_name Ns Oo Cm \&, Ns Ar action_name Oc Ns \&... Oc \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar pkg_fmri_pattern No \&...
.\" rebuild
.Nm Cm rebuild
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Fl \&-no-catalog
.Op Fl \&-no-index
.\" refresh
.Nm Cm refresh
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Fl \&-no-catalog
.Op Fl \&-no-index
.\" remove
.Nm Cm remove
.Op Fl n
.Op Fl d Ar YYYYMMDD
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Ar pkg_fmri_pattern \&...
.\" set
.Nm Cm set
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Ar section/property Ns Cm \&= Ns Cm \&( Ns Oo value Oc Ns Cm \&) No \&...
.\" verify
.Nm Cm verify
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.\" fix
.Nm Cm fix
.Op Fl v
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.\" diff
.Nm Cm diff
.Op Fl vq
.Op Fl \&-strict
.Op Fl \&-parsable
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar first_repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Fl s Ar second_repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.\" help
.Nm Cm help
.\" version
.Nm Cm version
.Sh DESCRIPTION
.Nm
provides the ability to create and manage
.Xr pkg 7
package repositories.
Package repositories are a predefined set of directories and files that permit
the storage and retrieval of package data by
.Xr pkg 1
and publication clients such as
.Xr pkgsend 1
or
.Xr pkgrecv 1 .
In addition, when network-based access to a package repository is needed,
.Xr pkg.depotd 8
can provide clients access to the repository to store and/or retrieve package
data.
.Sh OPTIONS
The following global options are supported:
.Bl -tag -width Ar
.It Fl ? | Fl \-help
Display a usage message.
.El
.\"
.Sh SUB-COMMANDS
.\" create
.Nm Cm create
.Op Fl \&-version Ar ver
.Ar uri_or_path
.Bd -ragged -offset Ds
Create a
.Xr pkg 7
repository at the specified location.
.Pp
This sub-command can only be used with filesystem-based repositories.
.Bl -tag -width Ar
.It Fl \&-version
Create a repository in a format compatible with the specified version.
By default, version 4 repositories are created.
Supported versions are:
.Bl -tag -width x
.It Sy 3
Supports storage of packages for a single publisher, catalog version 1, and
search version 1.
.It Sy 4
Supports storage of packages for multiple publishers, catalog version 1, and
search version 1.
.El
.El
.Ed
.Pp
.\" add-publisher
.Nm Cm add-publisher
.Fl s Ar repo_uri_or_path Ar publisher No \&...
.Bd -ragged -offset Ds
Add the specified publishers to the repository.
The new publishers have no packages or content.
.Pp
This sub-command can only be used with version 4 filesystem-based repositories.
.Bl -tag -width Ar
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.El
.Ed
.Pp
.\" remove-publisher
.Nm Cm remove-publisher
.Op Fl n
.Op Fl \&-synchronous
.Fl s Ar repo_uri_or_path
.Ar publisher No \&...
.Bd -ragged -offset Ds
Remove the specified publishers from the repository.
Remove all packages and all other data for the specified publishers.
.Pp
If the default publisher is removed, and only one publisher remains in the
repository, that remaining publisher becomes the default.
The publisher/prefix property of the repository is set to that remaining
publisher.
.Pp
If the default publisher is removed, and multiple publishers remain in the
repository, or if the last publisher is removed from the repository, the
publisher/prefix property is unset.
.Pp
This sub-command can only be used with version 4 filesystem-based repositories.
.Bl -tag -width Ar
.It Fl n
Perform a trial run of the operation with no publisher changes made.
The number of packages to be removed for each publisher is displayed before
exiting.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.It Fl \&-synchronous
Wait for the operation to complete before returning.
If this option is not specified, the command returns immediately while the
publisher is removed asynchronously in the background.
.El
.Ed
.Pp
.\" get
.Nm Cm get
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar section/property No \&...
.Bd -ragged -offset Ds
Display the property information for the repository or its publishers.
.Pp
By default, each property and its value are printed on separate lines.
Empty ASCII string values are represented by a pair of double quotation marks
.Pq Dq .
The following Bourne shell metacharacters, and newline, space, and tab, in
ASCII string values must be escaped by backslash characters
.Pq Sy \e
.Pp
\&; \&& \&( \&) \&| \&^ \&< \&> \e \&" \&' \&`
.Pp
See the
.Sx Examples
section for examples displaying publisher and repository properties.
.Pp
For a list of properties and the purpose and value of each property, see the
.Cm set
subcommand below.
.Bl -tag -width Ar
.It Fl F Ar format
Specify an alternative output format.
The value of format can be
.Cm tsv
.Pq Tab Separated Values ,
.Cm json
.Pq JavaScript Object Notation as a single line ,
or
.Cm json-formatted
.Pq JavaScript Object Notation, formatted for readability .
.It Fl H
Omit the headers from the listing.
.It Fl p Ar publisher
Display the property information for the given publisher.
The special value
.Cm all
displays the properties for all publishers.
This option can be specified multiple times.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.It Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
Use the
.Fl \&-key
option to specify a client SSL key file to use for package retrieval from an
HTTPS repository.
Use the
.Fl \&-cert
option to specify a client SSL certificate file to use for package retrieval
from an HTTPS repository.
This option pair can be specified multiple times.
.It Ar section/property
Display values for only the specified properties, such as
.Cm publisher/prefix
or
.Cm repository/version .
See the
.Cm set
subcommand for a complete list of properties.
.El
.Ed
.Pp
.\" info
.Nm Cm info
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Bd -ragged -offset Ds
Display a listing of the package publishers known by the repository.
The listing includes the number of packages for each
publisher, when the publisher's package data was last updated, and
the status of the publisher's package data
.Pq such as whether it is currently being processed .
.Bl -tag -width Ar
.It Fl p Ar publisher
Only display the data for the given publisher.
If not provided, the data for all publishers is displayed.
This option can be specified multiple times.
.El
.Pp
For descriptions of all other options, see the
.Nm Cm get
get command above.
.Ed
.Pp
.\" list
.Nm Cm list
.Op Fl F Ar format
.Op Fl H
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar pkg_fmri_pattern No \&...
.Bd -ragged -offset Ds
List the packages in the repo_uri_or_path repository that match the
specified
.Ar pkg_fmri_pattern patterns .
If no patterns are specified, all packages in the repository are listed.
The
.Ar pkg_fmri_pattern
pattern can include the \&? and \&* characters as
.Xr glob 3C
wildcards to match one or more packages.
.Pp
In the default output, the first column contains the name of the
publisher of the package.
The second column contains the name of the package.
The third column is a flag that shows the status of the package.
A value of o in the status column indicates the package is obsolete.
A value of r in the status column indicates the package has been renamed, which
is a form of obsoletion.
A value of l in the status column indicates that the package is legacy, meaning
that it will be removed in the future.
The fourth column contains the release and branch versions of the package.
See
.Xr pkg 7
for information about release and branch versions.
.Bl -tag -width Ar
.It Fl p Ar publisher
Only display the data for the given publisher.
If not provided, the data for all publishers is displayed.
This option can be specified multiple times.
.El
.Pp
For descriptions of all other options, see the
.Nm Cm get
get command above.
.Ed
.Pp
.\" contents
.Nm Cm contents
.Op Fl m
.Oo Fl t Ar action_name Ns Oo Cm \&, Ns Ar action_name Oc Ns \&... Oc \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Ar pkg_fmri_pattern No \&...
.Bd -ragged -offset Ds
List all packages in the
.Ar repo_uri_or_path repository .
If
.Ar pkg_fmri_pattern
is specified, display the contents
.Pq action attributes
of all matching packages in the repository.
.Bl -tag -width Ar
.It Fl m
Display all attributes of actions in the specified packages.
.It Fl t Ar action_name
Display only the specified actions in the specified packages.
The
.Fl t
option can be specified multiple times, or multiple actions can be specified as
the argument to one
.Fl t
option by separating the action names with commas.
The value of action_name is one of the actions listed in
.Em Actions
in the
.Xr pkg 7
man page, such as
.Cm file , Cm dir , Cm driver , Cm depend ,
or
.Cm set .
.El
.Pp
For descriptions of all other options, see the
.Nm Cm get
get command above.
.Ed
.Pp
.\" rebuild
.Nm Cm rebuild
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Fl \&-no-catalog
.Op Fl \&-no-index
.Bd -ragged -offset Ds
Discard all catalog, search, and other cached information found in the
repository, and then recreate it based on the current contents of the
repository.
.Bl -tag -width Ar
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
This option can be specified multiple times.
.It Fl \&-no-catalog
Do not rebuild package data.
.It Fl \&-no-index
Do not rebuild search indices.
.El
.Pp
For descriptions of all other options, see the
.Nm Cm get
get command above.
.Ed
.Pp
.\" refresh
.Nm Cm refresh
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Op Fl \&-no-catalog
.Op Fl \&-no-index
.Bd -ragged -offset Ds
Catalogue any new packages found in the repository and update all search
indices.
This is intended for use with deferred publication
.Po
.Fl \&-no-catalog
or
.Fl \&-no-index
options of
.Xr pkgsend 1
.Pc .
.Bl -tag -width Ar
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
This option can be specified multiple times.
.It Fl \&-no-catalog
Do not add any new packages.
.It Fl \&-no-index
Do not update search indices.
.El
.Pp
For descriptions of all other options, see the
.Nm Cm get
get command above.
.Ed
.Pp
.\" remove
.Nm Cm remove
.Op Fl n
.Op Fl d Ar YYYYMMDD
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Ar pkg_fmri_pattern \&...
.Bd -ragged -offset Ds
Remove packages that match the specified
.Ar pkg_fmri_pattern
pattern from the repository, including any files they reference that are
not in use by any other package.
The
.Ar pkg_fmri_pattern
pattern can include the \&? and \&* characters as
.Xr glob 3C
wildcards to match one or more packages.
.Pp
Note; all search index data for related publishers is removed.
This subcommand can be used only with file system based repositories.
.Pp
Caution; this operation is not reversible and should not be used while other
clients are accessing the repository since it might cause them to fail during
retrieval operations.
.Bl -tag -width Ar
.It Fl d Ar YYYYMMDD
Filter the list of packages to be removed to those which have the provided
.Ar YYYYMMDD
date as part of their full package version.
.It Fl n
Perform a trial run of the operation with no package changes made.
A list of the packages to be removed is displayed before exiting.
.It Fl p
Only remove matching packages for the given publisher.
If not provided, any matching packages are removed for all publishers.
This option can be specified multiple times.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.El
.Ed
.Pp
.\" set
.Nm Cm set
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Ar section/property Ns Cm \&= Ns Cm \&( Ns Oo value Oc Ns Cm \&) No \&...
.Bd -ragged -offset Ds
Set the value of the specified properties for the repository or publisher.
.Pp
This subcommand can be used only with file system based repositories.
.Bl -tag -width Ar
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.El
.Pp
Properties and values can be specified using one of the following forms:
.Bl -tag -width Ar
.It Ar section Ns \&/ Ns Ar property Ns Cm =
Clear the property value.
.It Ar section Ns \&/ Ns Ar property Ns Cm = Ns Ar value
Replace the property value with the given value.
.It Ar section Ns \&/ Ns Ar property Ns Cm = Ns \&( Ns Ar value1 Ar valueN \&)
Replace the property value with the list of values.
.El
.Pp
For repository versions 3 and 4, the following properties can be set for the
repository:
.Bl -tag -width Ar
.It Cm publisher/prefix
A string that represents the name of the default publisher.
The first character must be a-z, A-Z, or 0-9.
The remainder of the string can only contain the characters 0-9, -, ., a-z, and
A-Z.
This value indicates the publisher that should be used when more than one
publisher's packages are present, or when packages are published to the
repository and a publisher is not specified.
.El
.Pp
For repository versions 3 and 4, the following properties can be set for
individual publishers in the repository.
Use the
.Fl p
option to specify at least one publisher when you set these properties:
.Bl -tag -width Ar
.It Cm publisher/alias
A string that represents the default alias that clients should use when adding
a publisher using the repository's configuration data.
The first character must be a-z, A-Z, or 0-9.
The remainder of the string can only contain the characters 0-9, -, ., a-z, and
A-Z.
.It Cm repository/check-certificate-revocation
A boolean to check whether a certificate has been revoked.
When this property is set to True, the
.Nm Cm verify
and
.Nm Cm fix
commands attempt to contact any CRL distribution points in the certificates
used for signature verification to determine whether the certificate has been
revoked since being issued.
The default value is False.
This property is only used by the verify and fix subcommands to validate the
contents of the repository.
This property does not affect client settings.
This value should be the same as the corresponding
.Xr pkg 1
property value.
.It Cm repository/collection_type
Can have the value core or supplemental, indicating the type of packages
offered in this repository.
.Pp
The core type indicates that the repository contains all of the dependencies
declared by packages in the repository.
The core type is primarily used for operating system repositories.
.Pp
The supplemental type indicates that the repository contains packages that rely
on or are intended to be used with packages located in another repository.
.It Cm repository/description
A paragraph of plain text that describes the purpose and contents of the
repository.
.It Cm repository/detailed_url
A URI that represents the location of a document
.Pq such as a web page
that provides additional information about the repository.
.It Cm repository/format
The format used for storing catalogue files.
The default value is
.Cm ascii
which is the legacy format and should not be changed unless the repository will
be accessed solely by updated clients.
The other available value is
.Cm utf8
which allows clients to parse the catalogues faster and with less memory
overhead.
.It Cm repository/legal_uris
A list of locations
.Pq URIs
for documents that provide additional legal information about the repository.
.It Cm repository/mirrors
A list of locations
.Pq URIs
of repositories that contain a copy of the repository's package content but not
the package metadata.
.It Cm repository/name
A plain text string that contains the name of the repository.
.It Cm repository/origins
A list of locations
.Pq URIs
of repositories that contain a complete copy of the repository's package
metadata and content.
.It Cm repository/refresh_seconds
An integer value that represents the number of seconds clients should wait
before checking the repository for updated package data after each update
check.
.It Cm repository/registration_uri
A URI that represents the location of a resource that must be used to obtain
credentials for access to the repository.
A registration web page is one example.
.It Cm repository/related_uris
A list of locations
.Pq URIs
of repositories that contain packages that users might be interested in.
.It Cm repository/signature-required-names
A list of names that must be seen as common names of certificates while
validating the signatures of a package.
This property is only used by the verify and fix subcommands to validate the
contents of the repository.
This property does not affect client settings.
These values should be the same as the corresponding
.Xr pkg 1 property values.
.It Cm repository/trust-anchor-directory
The absolute path name of the directory that contains the trust anchors for
packages in this repository.
If not specified,
.Pq /etc/ssl/pkg/
is used.
This property is only used by the verify and fix subcommands to validate the
contents of the repository.
This property does not affect client settings.
This value should be the same as the corresponding
.Xr pkg 1
property value.
.El
.Pp
Properties not documented here, but listed in the output of the
.Cm get
subcommand, are reserved for internal use and should not be set.
.Ed
.Pp
.\" verify
.Nm Cm verify
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Bd -ragged -offset Ds
Verify that the following attributes of the package repository contents are
correct:
.Bl -bullet -width Ds -offset xxxx
.It
File checksums
.It
File permissions
.It
The path leading to the repository is also checked to ensure that the pkg5srv
user can read the repository contents.
This check can be necessary for repositories that are made available using the
svc:/application/pkg/server service, or using the
svc:/application/pkg/system-repository service when the system has non-global
zones.
.It
Package manifest permissions
.It
Package manifest content
.It
Package signatures
.Pp
Package manifest signatures are calculated based on the
values of the
.Cm repository/signature-required-names ,
.Cm repository/trust-anchor-directory ,
and
.Cm repository/check-certificate-revocation
properties.
.El
.Pp
Errors are emitted to stdout.
The command exits with a non-zero return code if any errors are emitted.
.Pp
This subcommand can be used only with version 4 file system based repositories.
.Bl -tag -width Ar
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
This option can be specified multiple times.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.El
.Ed
.Pp
.\" fix
.Nm Cm fix
.Op Fl v
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar repo_uri_or_path
.Bd -ragged -offset Ds
Fix the contents of a repository by first verifying the repository, and then
moving any invalid repository contents into a quarantine directory within the
repository.
.Pp
If repository errors are found, a repository rebuild is automatically
performed.
If any errors are found, a message is emitted to stdout showing which packages
must be re-imported using
.Xr pkgsend 1 or
.Xr pkgrecv 1 in order to restore the repository contents.
.Pp
This subcommand can be used only with version 4 file system based repositories.
.Bl -tag -width Ar
.It Fl v
Include output detailing the errors found during repository verification.
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
This option can be specified multiple times.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.El
.Ed
.Pp
.\" diff
.Nm Cm diff
.Op Fl vq
.Op Fl \&-strict
.Op Fl \&-parsable
.Oo Fl p Ar publisher Oc Ns \&...
.Fl s Ar first_repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Fl s Ar second_repo_uri_or_path
.Op Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
.Bd -ragged -offset Ds
Compare two repositories and show the differences.
.Pp
A
.Sy \&-
symbol in the beginning of an output line indicates the item was found only in
the first repository, while a
.Sy \&+
symbol indicates the item was found only in the second repository.
No symbol at the start of a line means that it is a common item.
.Bl -tag -width Ar
.It Fl v
Include output detailing the comparison including per-fmri output.
.It Fl \&-strict
Compare catalog last modified time stamp.
This is useful to determine whether one repository is an exact clone of another.
.It Fl \&-parsable
Generate parsable output in JSON format.
.It Fl p Ar publisher
Perform the operation only for the given publisher.
If not provided, or if the special value
.Cm all
is specified, the operation is performed for all publishers.
This option can be specified multiple times.
.It Fl s Ar repo_uri_or_path
Operate on the repository located at the given URI or file system path.
.It Fl \&-key Ar ssl_key Fl \&-cert Ar ssl_cert
Use the
.Fl \&-key
option to specify a client SSL key file to use for package retrieval from an
HTTPS repository.
Use the
.Fl \&-cert
option to specify a client SSL certificate file to use for package retrieval
from an HTTPS repository.
This option pair can be specified multiple times.
.El
.Ed
.Pp
.\" help
.Nm Cm help
.Bd -ragged -offset Ds
Display a usage message.
.Ed
.Pp
.\" version
.Nm Cm version
.Bd -ragged -offset Ds
Display a unique string that identifies the version of the
.Xr pkg 7
system.
The values produced by the version operation are not sortable and are not safe
for comparison beyond equality.
.Ed
.Sh EXAMPLES
.Bl -tag -width 6
.\"
.It Sy Example 1 No Create a Package Repository
.Bd -literal
    $ pkgrepo create /my/repository
.Ed
.It Sy Example 2 No Display Information
.Pp
Display a summary of publishers and the number of packages in a repository.
.Bd -literal
    $ pkgrepo info -s /my/repository
    PUBLISHER   PACKAGES STATUS UPDATED
    example.com 5        online 2011-07-22T18:09:09.769106Z

    $ pkgrepo info -s https://pkg.omnios.org/r151038/core/
    PUBLISHER PACKAGES STATUS           UPDATED
    omnios    863      online           2021-11-17T09:27:46.600621Z
.Ed
.It Sy Example 3 No Rebuild Catalogs and Search Data
.Pp
Rebuild the repository's catalogs and search data.
.Bd -literal
    $ pkgrepo rebuild -s /my/repository
.Ed
.It Sy Example 4 No Refresh Catalogs and Search Data
.Pp
Refresh the repository's catalogs and search data.
.Bd -literal
    $ pkgrepo refresh -s /my/repository
    $ pkgrepo refresh -s http://example.com/repository
.Ed
.It Sy Example 5 No Display All Repository Properties
.Bd -literal
    $ pkgrepo get -s /my/repository
    SECTION    PROPERTY VALUE
    publisher  prefix   ""
    repository version  4

    $ pkgrepo get -s https://pkg.omnios.org/r151040/core/
    SECTION    PROPERTY                     VALUE
    publisher  prefix                       omnios
    repository check-certificate-revocation False
    repository signature-required-names     ()
    repository trust-anchor-directory       /etc/ssl/pkg/
    repository version                      4
.Ed
.It Sy Example 6 No Display All Publisher Properties
.Bd -literal
    $ pkgrepo get -s https://pkg.omnios.org/r151040/core/ -p all
    PUBLISHER SECTION    PROPERTY         VALUE
    omnios    publisher  alias
    omnios    publisher  prefix           omnios
    omnios    repository collection-type  core
    omnios    repository description      Packages\ for\ OmniOS\ r151040
    omnios    repository legal-uris       ()
    omnios    repository mirrors          ()
    omnios    repository name             OmniOS\ r151040\ core
    omnios    repository origins          ()
    omnios    repository refresh-seconds
    omnios    repository registration-uri ""
    omnios    repository related-uris     ()
.Ed
.It Sy Example 7 No Set the Default Publisher
.Bd -literal
    $ pkgrepo set -s /my/repository publisher/prefix=example.com
.Ed
.It Sy Example 8 No Set a Publisher Property
.Bd -literal
    $ pkgrepo set -s /my/repository -p example.com \e
	repository/origins=http://example.com/repository
.Ed
.It Sy Example 9 No Add a New Publisher To the Repository
.Bd -literal
    $ pkgrepo add-publisher -s /my/repository example.com
.Ed
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It Sy 0
Command succeeded
.Pq or no differences encountered for pkgrepo diff .
.It Sy 1
An error occurred.
.It Sy 2
Invalid command line options were specified.
.It Sy 3
Multiple operations were requested, but only some of them succeeded.
.It Sy 4
No changes were made, nothing to do.
.It Sy 10
Differences found for pkgrepo diff.
.It Sy 99
An unanticipated exception occurred.
.El
.Sh INTERFACE STABILITY
The command line interface of
.Nm
is
.Sy Uncommitted .
The output of
.Nm
is
.Sy Not-An-Interface
and may change at any time.
.Sh SEE ALSO
.Xr pkg 1 ,
.Xr pkgrecv 1 ,
.Xr pkgsend 1 ,
.Xr glob 3C ,
.Xr pkg 7 ,
.Xr pkg.depotd 8
