#!/bin/ksh -p
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
# Copyright 2020 OmniOS Community Edition (OmniOSce) Association.
#

. /usr/lib/brand/ipkg/common.ksh
. /usr/lib/brand/shared/vars.ksh

ZONENAME=$1
ZONEPATH=$2
state=$3
cmd=$4
ALTROOT=$5

case $cmd in
    $ZONE_STATE_CMD_READY)
	setup_firewall
	;;
    $ZONE_STATE_CMD_HALT)
	is_brand_labeled
	if (( $? == 0 )); then
		# Leave the active dataset mounted after halting (this might be
		# a different dataset than what was mounted).
		mount_active_ds
	else
		# Umount dataset on the root.
		zoneroot="$ZONEPATH/root"
		umount $zoneroot || printf "$f_zfs_unmount" "$zoneroot"
	fi
	unconfig_network
	;;
esac

exit $ZONE_SUBPROC_OK
