#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.

#
# Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
# Copyright 2020 OmniOS Community Edition (OmniOSce) Association.
#

. /usr/lib/brand/ipkg/common.ksh
. /usr/lib/brand/shared/state.ksh

ZONENAME=$1
ZONEPATH=$2
state=$3
cmd=$4
ALTROOT=$5

case $cmd in
    $ZONE_STATE_CMD_READY)
	# Going to ready state
	# Mount active dataset on the root.
	mount_active_ds
	# Only configure the network if the zone is actually heading for boot
	[ "$state" != "$ZONE_STATE_SYSBOOT" ] && config_network
	;;

    $ZONE_STATE_CMD_BOOT)
	# Pre-boot
	;;
esac

exit $ZONE_SUBPROC_OK
